import { AssetCategory, AssetMetadata } from './types';

export const ASSET_CATALOG: Record<string, AssetMetadata> = {
  BTCUSDT: {
    symbol: 'BTCUSDT',
    name: 'Bitcoin / Tether USD',
    category: 'CRYPTO',
    baseCurrency: 'BTC',
    quoteCurrency: 'USDT',
    priceDecimals: 2,
    quantityDecimals: 5,
    tickSize: 0.01,
    exchange: 'Binance Spot',
    tradingHours: '24/7',
    primaryProvider: 'BINANCE',
    streamType: 'WEBSOCKET',
    streamEndpoint: 'wss://stream.binance.com:9443/ws/btcusdt@kline',
    description: 'Premier decentralized cryptocurrency asset benchmark.',
  },
  ETHUSDT: {
    symbol: 'ETHUSDT',
    name: 'Ethereum / Tether USD',
    category: 'CRYPTO',
    baseCurrency: 'ETH',
    quoteCurrency: 'USDT',
    priceDecimals: 2,
    quantityDecimals: 4,
    tickSize: 0.01,
    exchange: 'Binance Spot',
    tradingHours: '24/7',
    primaryProvider: 'BINANCE',
    streamType: 'WEBSOCKET',
    streamEndpoint: 'wss://stream.binance.com:9443/ws/ethusdt@kline',
    description: 'Decentralized smart contract protocol layer-1 benchmark.',
  },
  SOLUSDT: {
    symbol: 'SOLUSDT',
    name: 'Solana / Tether USD',
    category: 'CRYPTO',
    baseCurrency: 'SOL',
    quoteCurrency: 'USDT',
    priceDecimals: 2,
    quantityDecimals: 2,
    tickSize: 0.01,
    exchange: 'Binance Spot',
    tradingHours: '24/7',
    primaryProvider: 'BINANCE',
    streamType: 'WEBSOCKET',
    streamEndpoint: 'wss://stream.binance.com:9443/ws/solusdt@kline',
    description: 'High-throughput proof-of-history consensus execution layer.',
  },
  XAUUSD: {
    symbol: 'XAUUSD',
    name: 'Spot Gold / US Dollar (Золото)',
    category: 'METALS',
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
    priceDecimals: 2,
    quantityDecimals: 3,
    tickSize: 0.01,
    exchange: 'LBMA / COMEX Division',
    tradingHours: '24/5',
    primaryProvider: 'GOLD_API',
    backupProvider: 'COMEX',
    streamType: 'POLLING_REST',
    description: 'Global physical spot gold bullion institutional benchmark priced per troy ounce.',
  },
  EURUSD: {
    symbol: 'EURUSD',
    name: 'Euro / US Dollar',
    category: 'FOREX',
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    priceDecimals: 4,
    quantityDecimals: 2,
    tickSize: 0.0001,
    exchange: 'European Central Bank / Interbank FX',
    tradingHours: '24/5',
    primaryProvider: 'FRANKFURTER',
    streamType: 'POLLING_REST',
    description: 'World highest volume foreign exchange currency pair.',
  },
  GBPUSD: {
    symbol: 'GBPUSD',
    name: 'British Pound / US Dollar',
    category: 'FOREX',
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    priceDecimals: 4,
    quantityDecimals: 2,
    tickSize: 0.0001,
    exchange: 'Bank of England / Interbank FX',
    tradingHours: '24/5',
    primaryProvider: 'FRANKFURTER',
    streamType: 'POLLING_REST',
    description: 'British Pound Sterling versus US Dollar (Cable).',
  },
  NVDA: {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    category: 'EQUITIES',
    baseCurrency: 'NVDA',
    quoteCurrency: 'USD',
    priceDecimals: 2,
    quantityDecimals: 1,
    tickSize: 0.01,
    exchange: 'NASDAQ',
    tradingHours: 'US_EQUITIES',
    primaryProvider: 'YAHOO_EQUITIES',
    streamType: 'POLLING_REST',
    description: 'Leading accelerated computing and semiconductor enterprise.',
  },
  AAPL: {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    category: 'EQUITIES',
    baseCurrency: 'AAPL',
    quoteCurrency: 'USD',
    priceDecimals: 2,
    quantityDecimals: 1,
    tickSize: 0.01,
    exchange: 'NASDAQ',
    tradingHours: 'US_EQUITIES',
    primaryProvider: 'YAHOO_EQUITIES',
    streamType: 'POLLING_REST',
    description: 'Global consumer technology and ecosystem enterprise.',
  },
};

export function getAssetMetadata(symbol: string): AssetMetadata {
  const upper = symbol.toUpperCase();
  if (ASSET_CATALOG[upper]) {
    return ASSET_CATALOG[upper];
  }

  // Fallback metadata determination without arbitrary symbol guessing
  const isUsdtCrypto = upper.endsWith('USDT') || upper.endsWith('BTC');
  const isForex = upper.length === 6 && (upper.startsWith('EUR') || upper.startsWith('GBP') || upper.startsWith('USD') || upper.endsWith('USD'));

  return {
    symbol: upper,
    name: `${upper} Market Instrument`,
    category: isUsdtCrypto ? 'CRYPTO' : isForex ? 'FOREX' : 'COMMODITIES',
    baseCurrency: upper.slice(0, 3),
    quoteCurrency: upper.slice(3) || 'USD',
    priceDecimals: isForex ? 4 : 2,
    quantityDecimals: 2,
    tickSize: isForex ? 0.0001 : 0.01,
    exchange: isUsdtCrypto ? 'Binance' : isForex ? 'Interbank' : 'OTC Market',
    tradingHours: isUsdtCrypto ? '24/7' : '24/5',
    primaryProvider: isUsdtCrypto ? 'BINANCE' : 'FRANKFURTER',
    streamType: isUsdtCrypto ? 'WEBSOCKET' : 'POLLING_REST',
    description: `${upper} financial market asset`,
  };
}

export function getAllSupportedSymbols(): string[] {
  return Object.keys(ASSET_CATALOG);
}
